# Generated by Django 2.2.9 on 2020-01-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=64)),
                ('study_start_year', models.CharField(max_length=4)),
                ('unique_code', models.CharField(max_length=10)),
                ('quantity_of_students', models.CharField(max_length=3)),
            ],
        ),
    ]
