# Generated by Django 2.2.9 on 2020-01-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='unique_code',
        ),
        migrations.AlterField(
            model_name='group',
            name='quantity_of_students',
            field=models.PositiveIntegerField(),
        ),
    ]
