# Generated by Django 2.2.9 on 2020-01-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
