# Generated by Django 2.2.9 on 2020-01-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='quantity_of_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
