# Generated by Django 2.2.9 on 2020-01-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(max_length=128),
        ),
    ]
