# Generated by Django 2.2.9 on 2020-01-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20200119_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='quantity_of_students',
        ),
    ]
