# Generated by Django 2.2.9 on 2020-01-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20200126_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
