# Generated by Django 2.2.9 on 2020-01-29 18:48

from django.db import migrations, models


def forward(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all().only('id', 'telephone').iterator():
                                                                # чтоб экономить память и загружать частично
        student.telephone = ''.join(x for x in student.telephone if x.isdigit())
        student.save(update_fields=['telephone'])
        # изменяем не всю базу а лишь поле телефона (оптимизация)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20200129_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
        migrations.RunPython(forward),
    ]
