# Generated by Django 2.2.9 on 2020-02-03 17:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_auto_20200203_1701'),
        ('students', '0017_auto_20200129_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='specialization',
            field=models.CharField(blank=True, choices=[('biology', 'biology'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('mathematics', 'mathematics'), ('psychology', 'psychology'), ('linguistics', 'linguistics'), ('organizations', 'organizations'), ('computer_science', 'computer_science'), ('history', 'history')], default=None, max_length=64, null=True),
        ),
    ]
