# Generated by Django 2.2.9 on 2020-02-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20200203_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='repeat_the_password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
