# Generated by Django 2.2.9 on 2020-02-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_delete_studentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.SmallIntegerField(choices=[(1, 'GET'), (2, 'HEAD'), (3, 'POST'), (4, 'PUT'), (5, 'PATCH'), (6, 'DELETE'), (7, 'TRACE')])),
                ('time_delta', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
