# Generated by Django 2.2.9 on 2020-02-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_auto_20200206_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
