# Generated by Django 2.2.9 on 2020-01-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200126_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Master'), ('2', 'Ph.D'), ('3', 'M.D'), ('4', 'J.D.')], default=None),
        ),
    ]
