# Generated by Django 2.2.9 on 2020-01-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20200129_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.PositiveSmallIntegerField(choices=[('Master', 1), ('Ph.D', 2), ('M.D', 3), ('J.D.', 4)], default=None),
        ),
    ]
