# Generated by Django 2.2.9 on 2020-01-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20200129_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='academic_degree',
        ),
    ]
