# Generated by Django 2.2.9 on 2020-01-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_teacher_academic_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', 'Master'), ('2', 'Ph.D'), ('3', 'M.D'), ('4', 'J.D.')], default=None, null=True),
        ),
    ]
