# Generated by Django 2.2.9 on 2020-01-29 18:55

from django.db import migrations, models


def forward(apps, schema_editor):
    Teacher = apps.get_model('teachers', 'Teacher')
    for teacher in Teacher.objects.all().only('id', 'telephone').iterator():
                                                                # чтоб экономить память и загружать частично
        teacher.telephone = ''.join(x for x in teacher.telephone if x.isdigit())
        teacher.save(update_fields=['telephone'])
        # изменяем не всю базу а лишь поле телефона (оптимизация)


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_auto_20200129_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=65),
        ),
        migrations.RunPython(forward)
    ]
