# Generated by Django 2.2.9 on 2020-01-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_auto_20200129_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('1', 'Master'), ('2', 'Ph.D.'), ('3', 'M.D.'), ('4', 'J.D.')], default=None, max_length=64, null=True),
        ),
    ]
