# Generated by Django 2.2.9 on 2020-01-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_auto_20200129_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('Master', 'Master'), ('Ph.D', 'Ph.D.'), ('M.D.', 'M.D.'), ('J.D.', 'J.D.')], default=None, max_length=64, null=True),
        ),
    ]
